import { IProject } from '@/types';

export const INITIAL_PROJECTS: IProject[] = [
  {
    _id: 'proj_travertine_residence',
    title: 'Travertine Pavilion Residence',
    slug: 'travertine-pavilion-residence',
    tagline: 'A seamless integration of warm stone, cantilevered timber, and light shafts in Kyoto hills.',
    category: 'Residential',
    description: 'Designed as a dialogue between Japanese joinery and Roman travertine masonry. The residence floats above a natural terraced slope, offering panoramic forest vistas while maintaining passive geothermal thermal regulation. The structural envelope utilizes post-tensioned mass timber with light-filtering operable screens.',
    location: 'Kyoto, Japan',
    client: 'Private Estate',
    year: 2025,
    area: '820 sq.m',
    budget: '$4.2M',
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    beforeImage: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    afterImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
    ],
    blueprints: [
      {
        title: 'Ground Floor Level 00 Plan',
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
        level: 'Ground Floor',
        dimensions: '28.4m x 19.6m',
      },
      {
        title: 'Cantilevered Pavilion Elevation',
        image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80',
        level: 'North/South Section',
        dimensions: 'Height: 8.8m',
      },
    ],
    specs: [
      { label: 'Structural System', value: 'Post-tensioned mass timber & travertine core' },
      { label: 'Energy Certification', value: 'Passivhaus Premium / Net Zero' },
      { label: 'Acoustic Rating', value: 'Rw + Ctr 58 dB' },
      { label: 'Solar Exposure', value: 'Optimized Southern orientation with louvers' },
    ],
    features: [
      'Double-height biophilic atrium with rainwater collection',
      'Hydronic underfloor heating & cooling embedded in stone',
      'Subterranean wine cellar and meditation gallery',
      'Triple-glazed low-iron acoustic curtain wall',
    ],
    architectLeader: {
      name: 'Elena Vance, FAIA',
      role: 'Lead Design Principal',
      avatar: '/images/team1.png',
    },
    status: 'Award Winner',
    featured: true,
    awards: ['Mies Crown Hall Americas Prize Finalist 2025', 'World Architecture Festival Best Villa 2024'],
  },
  {
    _id: 'proj_nordic_energy_hub',
    title: 'Nordic Clean Energy Hub',
    slug: 'nordic-clean-energy-hub',
    tagline: 'A sculptural carbon-negative workplace and geothermal innovation center in Oslo.',
    category: 'Commercial',
    description: 'A benchmark in sustainable corporate architecture. Built entirely from locally harvested cross-laminated timber (CLT) and recycled aluminum shingle facade, generating 140% of its operational energy needs.',
    location: 'Oslo, Norway',
    client: 'EquiNordic Technologies',
    year: 2025,
    area: '14,500 sq.m',
    budget: '$28.5M',
    heroImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
    beforeImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80',
    afterImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=80',
    ],
    blueprints: [
      {
        title: 'Typical Workstation Mezzanine',
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
        level: 'Level 03-07',
        dimensions: '42m x 36m',
      },
    ],
    specs: [
      { label: 'Structural System', value: 'Engineered Glulam + CLT Diagrid' },
      { label: 'LEED Status', value: 'LEED Platinum Certified (98 pts)' },
      { label: 'Embodied Carbon', value: '-380 kg CO2e / sq.m' },
    ],
    features: [
      'Central helical timber public atrium',
      'Rooftop urban biodiversity garden and solar microgrid',
      'Automated motorized airflow louvers',
    ],
    architectLeader: {
      name: 'Julian Sterling',
      role: 'Director of Sustainable Engineering',
      avatar: '/images/team2.png',
    },
    status: 'Completed',
    featured: true,
    awards: ['BREEAM International Award 2025', 'European Timber Structure of the Year'],
  },
  {
    _id: 'proj_terracotta_cultural',
    title: 'The Terracotta Monolith Cultural Center',
    slug: 'terracotta-monolith-cultural-center',
    tagline: 'Ribbed ceramic panels wrapping a public civic theater and architectural gallery.',
    category: 'Interior & Cultural',
    description: 'An homage to ancient clay ceramics combined with ultra-modern parametric acoustics. The facade changes tone with the passing sun, casting dynamic shadows into the subterranean amphitheater.',
    location: 'Valencia, Spain',
    client: 'City of Valencia Department of Arts',
    year: 2024,
    area: '6,800 sq.m',
    budget: '$16.8M',
    heroImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=1600&q=80',
    ],
    blueprints: [
      {
        title: 'Amphitheater Section A-A',
        image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80',
        level: 'Main Auditorium',
        dimensions: '900 seats capacity',
      },
    ],
    specs: [
      { label: 'Facade Cladding', value: 'Custom extruded terracotta rainscreen' },
      { label: 'Reverberation Time', value: '1.4s calibrated for symphonic & acoustic speech' },
    ],
    features: [
      'Sculpted plaster acoustic ceiling sails',
      'Natural daylight skylights with UV attenuation',
      'Community open workshop and makerspace',
    ],
    architectLeader: {
      name: 'Amara Chen',
      role: 'Cultural & Civic Studio Lead',
      avatar: '/images/team3.png',
    },
    status: 'Completed',
    featured: true,
    awards: ['Civic Design Excellence Award 2024'],
  },
  {
    _id: 'proj_verdant_masterplan',
    title: 'Verdant Linear Urban Masterplan',
    slug: 'verdant-linear-urban-masterplan',
    tagline: 'Transforming 40 hectares of decommissioned port infrastructure into a biophilic eco-district.',
    category: 'Urban Masterplan',
    description: 'A 15-minute city masterplan integrating pedestrian canals, modular affordable mass-timber housing, wetland restoration, and autonomous electric micro-transit.',
    location: 'Rotterdam, Netherlands',
    client: 'Rotterdam Waterfront Authority',
    year: 2026,
    area: '400,000 sq.m',
    budget: '$140M',
    heroImage: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1600&q=80',
    ],
    blueprints: [
      {
        title: 'District Zoning & Hydrodynamic Plan',
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
        level: 'Masterplan Grid',
        dimensions: '1.2km Waterfront',
      },
    ],
    specs: [
      { label: 'Walkability Score', value: '99 / 100 15-minute radius' },
      { label: 'Renewable Generation', value: '100% on-site wind + solar' },
    ],
    features: [
      'Continuous 4km public waterfront promenade',
      'Sponge-city bioswales handling 100-year storm events',
      'Modular mass-timber residential blocks',
    ],
    architectLeader: {
      name: 'Marcus Thorne',
      role: 'Urban Strategy & Masterplanning Partner',
      avatar: '/images/team4.png',
    },
    status: 'Under Construction',
    featured: true,
    awards: ['Global Urbanism Green Award 2026'],
  },
  {
    _id: 'proj_cascade_villa',
    title: 'Cascade Glass Villa',
    slug: 'cascade-glass-villa',
    tagline: 'Cantilevered glass volumes suspended over a natural waterfall in Zurich hills.',
    category: 'Residential',
    description: 'An architectural feat of high-tensile structural steel and structural glass. The living room hovers 12 meters over a mountain stream with seamless sliding glass walls.',
    location: 'Zurich, Switzerland',
    client: 'Private Client',
    year: 2025,
    area: '650 sq.m',
    budget: '$5.6M',
    heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
    ],
    blueprints: [
      {
        title: 'Cantilever Structural Detail',
        image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80',
        level: 'Upper Deck',
        dimensions: '14m Cantilever',
      },
    ],
    specs: [
      { label: 'Cantilever Reach', value: '14.2 meters unsupported' },
      { label: 'Glazing', value: 'Electrically switchable smart tint glass' },
    ],
    features: [
      'Infinity plunge pool cascading into lower ravine',
      'Integrated smart lighting mimicking natural circadian rhythm',
      'Natural stone cladding quarried from surrounding mountain',
    ],
    architectLeader: {
      name: 'Elena Vance, FAIA',
      role: 'Lead Design Principal',
      avatar: '/images/team1.png',
    },
    status: 'Completed',
    featured: false,
    awards: ['Swiss Architecture Selection 2025'],
  },
  {
    _id: 'proj_solar_helix',
    title: 'Solar Helix Sustainable Campus',
    slug: 'solar-helix-sustainable-campus',
    tagline: 'A self-cooling research laboratory wrapped in kinetic photovoltaic petals.',
    category: 'Sustainable',
    description: 'Combining biomimetic facade design with advanced thermal mass cooling. The kinetic louvers follow the solar angle to minimize solar gain while maximizing natural diffuse day-lighting.',
    location: 'Melbourne, Australia',
    client: 'Renewable Future Institute',
    year: 2025,
    area: '9,200 sq.m',
    budget: '$21.0M',
    heroImage: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80',
    ],
    blueprints: [
      {
        title: 'Kinetic Solar Facade Section',
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
        level: 'Facade Detail',
        dimensions: '3.6m Module',
      },
    ],
    specs: [
      { label: 'Energy Self-Sufficiency', value: '118% Net Positive' },
      { label: 'Solar Output', value: '420 kWp rooftop + facade array' },
    ],
    features: [
      'Rainwater aquifer recharge filtration basin',
      'Natural night-purge stack ventilation towers',
      'Timber-composite zero-portland concrete hybrid structure',
    ],
    architectLeader: {
      name: 'Julian Sterling',
      role: 'Director of Sustainable Engineering',
      avatar: '/images/team2.png',
    },
    status: 'Completed',
    featured: false,
    awards: ['Australian Sustainability Excellence 2025'],
  },
];
